package exceptionsdemo;

import java.util.Scanner;

/**
 * Author  :Sola.Sri
 * Date    :Sep 6, 2025
 * Time    :2:23:05â€¯PM  
 * project :CoreJava
*/

public class DivisionDemo {

	public static void main(String[] args) {

        int a, b, result;
        Scanner input = new Scanner(System.in);

        System.out.println("Input two integers :");
        a = input.nextInt();
        b = input.nextInt();
       
        try {
        result = a / b;
        System.out.println("Result = " + result);
        }
        catch(ArithmeticException e)
        {
        	System.err.println("Exception caught:Division by zero."+e);
        }
        finally {
        	  input.close();//
        	  System.out.println("In Finally Block");
        }
        
	}

}
